Autocommands for tab events
pentadactyl/pentadactyl pull request #18
Opened 2019-08-26 02:20 UTC by reaysawa

They do not bring along any relevant arguments at the moment (e.g. a `tab` argument for TabSelect) because it doesn't seem obvious on how to add them, nor there's a need for them at the moment (at least as far as my usage is concerned).

For TabSelect, it seems like the event's upbringing outlives the tab reference somehow, so it's something to look out for if implementing those arguments in the future.

2019-08-27 02:22 UTC, jackrosenthal requested changes
looking good! thanks for contributing

2019-08-27 02:22 UTC, jackrosenthal commented on common/content/tabs.js
> +            events.listen(tabContainer, event, () => callback(event), false);
might it be cleaner to move the definition of `callback` into the body of the `for` to avoid the lambda? Also don't have to pass `event` then either.

2019-08-27 02:22 UTC, jackrosenthal commented on common/content/tabs.js
>          modes.reset();
The `TODO` above might no longer be relevant/confuse. Can you remove while you're here?

2019-09-01 09:53 UTC, reaysawa commented
@jackrosenthal finally got my shit together to handle this. Sorry for the delay.

I'll try to act as quick as possible on any further changes you might suggest, so that we can get this out of the way as soon as possible. Cheers!

2019-09-03 23:53 UTC, jackrosenthal commented
lgtm. ready to merge?

2019-09-04 04:39 UTC, reaysawa commented
sure! Those changes are very simplistic, but I think what's being inserted in this PR can be easily be improved upon later if need be. I didn't find any bugs or weirdness for the past week of usage.

2019-09-05 19:21 UTC, merged